encyclopedia/urls.py
from django.urls import path
from . import contact
from . import views

app_name = "wiki"
urlpatterns = [
    path("/", views.index, name="index"),
    path("/new", views.new, name="new"),
    path("/random", views.randomentry, name="random"),
    path("/contact", contact.contact, name='contact'), 
    path("/search", views.search, name="search"),

    path("/edit/<str:entry_name>", views.edit, name="edit"),
    path("/<str:entry_name>", views.entry, name="entry"),
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from logging import PlaceHolder
from re import X
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
import random
import markdown2
from markdown2 import Markdown

class NewWikiEntry(forms.Form):
    name = forms.CharField(label="New Entry Name", max_length=100)
    content = forms.CharField(label="New Entry Text", widget=forms.Textarea)


class EditWikiEntry(forms.Form):
    name = forms.CharField(label="Entry Name", required=False, max_length=100, widget=forms.TextInput(attrs={'readonly':'readonly'}))
    content = forms.CharField(label="Edit Entry Text", required=False, widget=forms.Textarea)


class NewWikiSearch(forms.Form):
    searchtext = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'placeholder': 'Search'}))

def entry(request, entry_name):
    if util.get_entry(entry_name) is None:
        return render(request, "encyclopedia/entry.html", {
            "title": "There is no such Entry: " + entry_name,
            "content": "",
            "form1": NewWikiSearch(request.GET)
        })
    
    markdowner = Markdown()
    return render(request, "encyclopedia/entry.html", {
        "title": entry_name,
        #"content": util.get_entry(entry_name), ###  Markdown here!!!  ###
        "content": markdowner.convert(util.get_entry(entry_name)), #Markdown here!!!
        "form1": NewWikiSearch(request.GET)
})

def edit(request, entry_name):
    if request.method == "POST":
        form2 = EditWikiEntry(request.POST)
        if form2.is_valid():
            newcontent = form2.cleaned_data["content"]
            util.save_entry(entry_name, newcontent)
            return render(request, "encyclopedia/entry.html", {
                    "title": entry_name,
                    "content": markdown2.markdown(util.get_entry(entry_name)),
                    "form1": NewWikiSearch(request.GET)
                })
    return render(request, "encyclopedia/edit.html", {
        "title": entry_name,
        "form2": EditWikiEntry(initial={'name': entry_name, 'content': util.get_entry(entry_name)}),
        "form1": NewWikiSearch(request.GET)
    })


def new(request):
    if request.method == "POST":
        form = NewWikiEntry(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            content = form.cleaned_data["content"]
            if name in util.list_entries():
                # change HTML -> ErrorMessage
                return render(request, "encyclopedia/index.html", { ## todo
                    "title": "The Entry <"+name+"> already exists!",
                    "entries": "",
                    "form1": NewWikiSearch(request.GET)
                })
            util.save_entry(name, content)
            return render(request, "encyclopedia/entry.html", {
                "title": name,
                "content": content,
                "form1": NewWikiSearch(request.GET)
            })
        else:
            return render(request, "wiki/new.html", {
                "form": form,
                "form1": NewWikiSearch(request.GET)
            })
    return render(request, "encyclopedia/new.html", {
        "form": NewWikiEntry(),
        "form1": NewWikiSearch(request.GET)
    })


def index(request):
    return render(request, "encyclopedia/index.html", {
        "title": "All Pages",
        "entries": util.list_entries(),
        "form1": NewWikiSearch(request.GET)
    })



def randomentry(request):
    entries = util.list_entries()
    number = random.randint(1,len(entries))
    entry_name = entries[number-1]
    return render(request, "encyclopedia/entry.html", {
        "title": entry_name,
        "content": markdown2.markdown(util.get_entry(entry_name)),
        "form1": NewWikiSearch(request.GET)
})


def search(request):
    form1 = NewWikiSearch(request.GET)
    if form1.is_valid():
        searchtext = form1.cleaned_data["searchtext"]
        entries = util.list_entries()
        #CAPITALIZE THE SEARCHTEXT AND ENTRIES???
        if searchtext in entries:  #es gibt den searchtext --> öffne entry mit content
            return render(request, "encyclopedia/entry.html", {
                "title": searchtext,
                "content": util.get_entry(searchtext),
                "form1": form1
            })
        substrings = list()
        for entry in entries:
            if searchtext in entry:
                substrings.append(entry)
        if not substrings:
            print(111)
            return render(request, "encyclopedia/entry.html", {
                "title": "No Matching Search Results",
                "content": "Try searching for something different!",
                "form1": form1
            })
        return render(request, "encyclopedia/index.html", {
            "title": "Your Search was a substring of the these Entries:",
            "entries": substrings,
            "form1": form1
        })
    return render(request, "encyclopedia/index.html", {
        "title": "All Pages",
        "entries": util.list_entries(),
        "form1": form1
    }) 

encyclopedia/templates/encyclopedia/contact.html
<!DOCTYPE html>
{% extends "encyclopedia/layout.html" %}

{% block title %}Encyclopedia{% endblock %}

{% block body %}
    <h1>Contact us</h1>

{% if submitted %}
<p class="success">
Your message was submitted successfully. Thank you.
</p>
 
{% else %}
  <form action="" method="post" novalidate>
  <table>
    {{ form.as_table }}
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" value="Submit"></td>
    </tr>
  </table>
  {% csrf_token %}
  </form>
{% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
<!DOCTYPE html>
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page:  {{ title }}</h1>
    <br>
    <form action="{% url 'wiki:edit' title %}" method="post">
        {% csrf_token %}
        <table>
        {{ form2.as_table }}


        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Save Entry"></td>
        </tr>

        </table>
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
<!DOCTYPE html>
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}
    <h1>Wiki Entry: {{ title }}</h1>
    <div>{{ content | safe}}</div><br>
    <br>
    <br>
    <br>
    <a href="/wiki/edit/{{ title }}">edit {{ title }}</a><br>

{% endblock %}




    <!-- <form action="{% url 'wiki:edit' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="edit">
    </form> -->

encyclopedia/templates/encyclopedia/index.html
<!DOCTYPE html>
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <ul>
        {% for entry in entries %}
            <a href="/wiki/{{ entry }}">{{ entry }}</a><br>
            
        {% endfor %}
    </ul>

{% endblock %}

                <!-- <div>
                    <a href="{% url 'entry' %}">Entry</a>
                </div> -->

encyclopedia/templates/encyclopedia/layout.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <!-- HTML FORM 
                <form action="{% url 'wiki:search' %}" method="GET">
                    {% csrf_token %}
                    <input class="search" type="text" name="searchtext" placeholder="Search Encyclopedia">
                </form>
                -->
                <!-- DJANGO FORM -->
                <form action="{% url 'wiki:search' %}" method="get">
                    {% csrf_token %}
                    <table>
                    {{ form1 }}         
            
                    <!-- <tr>
                        <td>&nbsp;</td>
                        <td><input type="submit" value="Save Entry"></td>
                    </tr> -->
            
                    </table>
                </form>

                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                <br>
                <!-- <div>
                    <a href="{% url 'wiki:contact' %}">Contact</a>
                </div> -->
                
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
<!DOCTYPE html>
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Entry</h1>

    <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}

        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Save Entry"></td>
        </tr>

        </table>
    </form>

{% endblock %}